### PR TITLE
Heres my Vivve fest 7 submission

### PR DESCRIPTION
**Pull request by KenwoodFox**
Vivve Fest 7

### CODE REVIEW

**Comment by RealConar** [comment]
Vivve%20Fest%206 (3) (2)

**Comment by KenwoodFox** [comment]
> Vivve%20Fest%206 (3) (2)

This is looking awesome <3 should prolly be in its own PR tho lol~

**Comment by RealConar** [comment]
> > Vivve%20Fest%206 (3) (2)
> 
> This is looking awesome <3 should prolly be in its own PR tho lol~

Sorry I don't know how to Github :p

**Comment by KenwoodFox** [comment]
Lol its ok @RealConar :P i can put the files in for you if u want, 

if you clone this whole repo down, u can put all ur files in the same place i did but, just on a different branch

**Comment by KenwoodFox** [comment]
This one did not make the cut.

**Pull request closed without merging**
